site_name: session_tracker
site_description: Tracks session information
repo_url: https://github.com/rolagzza/session-tracker
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/rolagzza">rolagzza</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
