# Generated by Django 3.1.2 on 2020-10-06 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('resolution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.resolution')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('country_iso2', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SessionActionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('BUY', 'BUY'), ('REVIEW', 'REVIEW'), ('SHOPPING-CART', 'SHOPPING-CART')], default='LOGIN', max_length=15)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.sessionaction')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.sessionlocationdetails')),
            ],
        ),
    ]
